#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: be3faa5
#
# Source0 file verified with key 0x3D6A49E4C4E0B673 (ludvig.michaelsson@gmail.com)
#
Name     : pam_u2f
Version  : 1.3.2
Release  : 1
URL      : https://developers.yubico.com/pam-u2f/Releases/pam_u2f-1.3.2.tar.gz
Source0  : https://developers.yubico.com/pam-u2f/Releases/pam_u2f-1.3.2.tar.gz
Source1  : https://developers.yubico.com/pam-u2f/Releases/pam_u2f-1.3.2.tar.gz.sig
Source2  : 3D6A49E4C4E0B673.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pam_u2f-bin = %{version}-%{release}
Requires: pam_u2f-lib = %{version}-%{release}
Requires: pam_u2f-license = %{version}-%{release}
Requires: pam_u2f-man = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : buildreq-configure
BuildRequires : gnupg
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libfido2)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
= Pluggable Authentication Module (PAM) Universal 2nd Factor (U2F)
image:https://github.com/yubico/pam-u2f/workflows/linux/badge.svg["Linux Build Status (github actions)", link="https://github.com/Yubico/pam-u2f/actions"]
image:https://github.com/yubico/pam-u2f/workflows/macos/badge.svg["macOS Build Status (github actions)", link="https://github.com/Yubico/pam-u2f/actions"]
image:https://github.com/yubico/pam-u2f/workflows/fuzzer/badge.svg["Fuzz Status (github actions)", link="https://github.com/Yubico/pam-u2f/actions"]

%package bin
Summary: bin components for the pam_u2f package.
Group: Binaries
Requires: pam_u2f-license = %{version}-%{release}

%description bin
bin components for the pam_u2f package.


%package lib
Summary: lib components for the pam_u2f package.
Group: Libraries
Requires: pam_u2f-license = %{version}-%{release}

%description lib
lib components for the pam_u2f package.


%package license
Summary: license components for the pam_u2f package.
Group: Default

%description license
license components for the pam_u2f package.


%package man
Summary: man components for the pam_u2f package.
Group: Default

%description man
man components for the pam_u2f package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 3D6A49E4C4E0B673' gpg.status
%setup -q -n pam_u2f-1.3.2
cd %{_builddir}/pam_u2f-1.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740524585
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1740524585
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pam_u2f
cp %{_builddir}/pam_u2f-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pam_u2f/2f3f94378eea34620d6f9630dce41ff71cac44d0 || :
export GOAMD64=v2
GOAMD64=v2
%make_install
## install_append content
# Put security libs in the right place
mkdir -p %{buildroot}/usr/lib64/security
mv %{buildroot}/lib/x86_64-linux-gnu/security/pam_*.so %{buildroot}/usr/lib64/security/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pamu2fcfg

%files lib
%defattr(-,root,root,-)
/usr/lib64/security/pam_u2f.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pam_u2f/2f3f94378eea34620d6f9630dce41ff71cac44d0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pamu2fcfg.1
/usr/share/man/man8/pam_u2f.8
